export const siteConfig = {
  name: "Portal Terrenos",
  shortName: "Portal Terrenos",
  description:
    "Lotes y terrenos urbanos y campestres en Cajamarca, Perú. Invierte en tu futuro con asesoría personalizada de Abraham Saul Portal Garcia. Garantía jurídica, títulos de propiedad limpios.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://portalterrenos.pe",
  ogImage: "/og-image.png",
  keywords: [
    "lotes",
    "terrenos",
    "inmobiliaria",
    "inversión inmobiliaria",
    "lotes urbanos",
    "terrenos en venta",
    "proyecto inmobiliario",
    "Abraham Portal",
    "asesor inmobiliario",
    "Cajamarca",
    "Santa Margarita Polloc",
    "Alameda La Colpa",
    "La Finca",
    "Planicies del Valle",
    "Valle 4",
    "Valle 5",
    "Valle 6",
    "Valle 7",
    "La Pirca",
    "perú",
  ],
  author: "Abraham Saul Portal Garcia",
  locale: "es_PE",
  phone: "+51 926 301 972",
  email: "contacto@portalterrenos.pe",
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "51926301972",
  whatsappDefaultMessage:
    process.env.NEXT_PUBLIC_WHATSAPP_MESSAGE ||
    "Hola Abraham! Vi tu web PortalTerrenos.pe y quiero más información sobre los lotes disponibles en Cajamarca.",
  address: "Cajamarca, Perú",
  projectName: "Cartera Inmobiliaria Cajamarca",
  advisor: {
    name: "Abraham Saul Portal Garcia",
    role: "Asesor Inmobiliario Autorizado · Cajamarca",
    credentials: "Registro Inmobiliario Oficial",
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "51926301972",
    calendly: "https://calendly.com/portalterrenos/visita",
    photo: "/foto-abraham.jpg",
  },
  region: "Cajamarca",
  currency: "PEN",
  currencySymbol: "S/",
};

export type SiteConfig = typeof siteConfig;
